/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Handle Discord OAuth callback, mint a session cookie, and redirect to the frontend dashboard. */
    get: operations['callback_handler']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Begin Discord OAuth flow and set a short-lived state cookie. */
    get: operations['login_handler']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return the currently authenticated user. */
    get: operations['me_handler']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/deployments/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List every stored deployment. */
    get: operations['list_deployments_handler']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/deployments/{guild_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Fetch a single deployment by guild id. */
    get: operations['get_deployment_handler']
    put?: never
    /** Create or update a deployment for a guild. */
    post: operations['upsert_deployment_handler']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/guilds/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List guilds where the user is an admin and the bot is present. */
    get: operations['list_guilds_handler']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check API liveness. */
    get: operations['health_check']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tokens/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List tokens for the authenticated user. */
    get: operations['list_tokens_handler']
    put?: never
    /** Mint a new API token for the authenticated user. */
    post: operations['create_token_handler']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tokens/{token_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a token by id. */
    delete: operations['delete_token_handler']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Response envelope for /auth/me. */
    AuthResponse: {
      user: components['schemas']['AuthUser']
    }
    /** @description API representation of the authenticated user. */
    AuthUser: {
      avatar?: string | null
      global_name?: string | null
      id: string
      username: string
    }
    /** @description Create-token payload. */
    CreateTokenRequest: {
      label?: string | null
    }
    /** @description Token creation response (includes plaintext token). */
    CreateTokenResponse: {
      token: string
    }
    /** @description Body for creating or replacing a deployment. */
    DeploymentRequest: {
      /** @description Raw source code for the guild bot. */
      code: string
    }
    /** @description API representation of a deployment. */
    DeploymentResponse: {
      created_at: string
      guild_id: string
      source?: string | null
      updated_at: string
    }
    /** @description Canonical error envelope returned by the HTTP API. */
    ErrorResponse: {
      /** @description Human readable error message. */
      message: string
    }
    /** @description Guild info exposed by the API. */
    GuildResponse: {
      icon?: string | null
      id: string
      name: string
      /** Format: int64 */
      permissions: number
    }
    /** @description Token list item. */
    TokenResponse: {
      created_at: string
      label?: string | null
      last_used_at?: string | null
      token_id: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  callback_handler: {
    parameters: {
      query: {
        /** @description Discord authorization code */
        code: string
        /** @description Opaque state value returned by Discord */
        state: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect response with cookies */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  login_handler: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect response */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  me_handler: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            user: components['schemas']['AuthUser']
          }
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  list_deployments_handler: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            created_at: string
            guild_id: string
            source?: string | null
            updated_at: string
          }[]
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  get_deployment_handler: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Discord guild id */
        guild_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            created_at: string
            guild_id: string
            source?: string | null
            updated_at: string
          }
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  upsert_deployment_handler: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Discord guild id */
        guild_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DeploymentRequest']
      }
    }
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            created_at: string
            guild_id: string
            source?: string | null
            updated_at: string
          }
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  list_guilds_handler: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            icon?: string | null
            id: string
            name: string
            /** Format: int64 */
            permissions: number
          }[]
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  health_check: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description API is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/plain': string
        }
      }
    }
  }
  list_tokens_handler: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            created_at: string
            label?: string | null
            last_used_at?: string | null
            token_id: string
          }[]
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  create_token_handler: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTokenRequest']
      }
    }
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            token: string
          }
        }
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
  delete_token_handler: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Token identifier */
        token_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Token deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Human readable error message. */
            message: string
          }
        }
      }
    }
  }
}
