// This file is auto-generated by typegen. Do not edit manually.

export type JsonValue =
  | number
  | string
  | boolean
  | Array<JsonValue>
  | { [key in string]?: JsonValue }
  | null

/**
 * A Discord user.
 *
 * [Discord docs](https://discord.com/developers/docs/resources/user#user-object).
 */
export type EventUser = {
  /** The user's unique snowflake ID. */
  id: string
  /** The user's username (not unique across Discord). */
  username: string
  /** The user's Discord-tag (discriminator), if any. */
  discriminator?: number
  /** Whether this user is a bot account. */
  bot: boolean
}

/**
 * A member of a guild.
 *
 * [Discord docs](https://discord.com/developers/docs/resources/guild#guild-member-object).
 */
export type EventMember = {
  /** The user this member represents. */
  user: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  /** The member's guild-specific nickname. */
  nick?: string
  /** The member's guild-specific avatar hash. */
  avatar?: string
  /** Role IDs assigned to this member. */
  roles: string[]
  /** ISO8601 timestamp when the member joined the guild. */
  joinedAt?: string
  /** ISO8601 timestamp when the member started boosting the guild. */
  premiumSince?: string
  /** Whether the member is deafened in voice channels. */
  deaf: boolean
  /** Whether the member is muted in voice channels. */
  mute: boolean
  /** Guild member flags. */
  flags: number
  /** Whether the member has not yet passed the guild's membership screening. */
  pending: boolean
  /** Total permissions of the member in the channel (only in interactions). */
  permissions?: string
  /** ISO8601 timestamp when the member's timeout expires. */
  communicationDisabledUntil?: string
}

/**
 * A message sent in a channel.
 *
 * [Discord docs](https://discord.com/developers/docs/resources/message#message-object).
 */
export type EventMessage = {
  /** The user's unique snowflake ID. */
  id: string
  /** The channel the message was sent in. */
  channelId: string
  /** The guild the message was sent in (if applicable). */
  guildId?: string
  /** The message content. */
  content: string
  /** The author of the message. */
  author: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  /** Member properties of the author (if sent in a guild). */
  member?: {
    /** The user this member represents. */
    user: {
      /** The user's unique snowflake ID. */
      id: string
      /** The user's username (not unique across Discord). */
      username: string
      /** The user's Discord-tag (discriminator), if any. */
      discriminator?: number
      /** Whether this user is a bot account. */
      bot: boolean
    }
    /** The member's guild-specific nickname. */
    nick?: string
    /** The member's guild-specific avatar hash. */
    avatar?: string
    /** Role IDs assigned to this member. */
    roles: string[]
    /** ISO8601 timestamp when the member joined the guild. */
    joinedAt?: string
    /** ISO8601 timestamp when the member started boosting the guild. */
    premiumSince?: string
    /** Whether the member is deafened in voice channels. */
    deaf: boolean
    /** Whether the member is muted in voice channels. */
    mute: boolean
    /** Guild member flags. */
    flags: number
    /** Whether the member has not yet passed the guild's membership screening. */
    pending: boolean
    /** Total permissions of the member in the channel (only in interactions). */
    permissions?: string
    /** ISO8601 timestamp when the member's timeout expires. */
    communicationDisabledUntil?: string
  }
}

/**
 * Payload for a message update event.
 *
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#message-update).
 */
export type EventMessageUpdate = {
  /** The user's unique snowflake ID. */
  id: string
  /** The channel the message was sent in. */
  channelId: string
  /** The guild the message was sent in (if applicable). */
  guildId?: string
  /** The message content. */
  content?: string
  /** The author of the message. */
  author?: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  /** ISO8601 timestamp when the message was edited. */
  editedTimestamp?: string
  /** The cached old message before the update (if available). */
  old?: {
    /** The user's unique snowflake ID. */
    id: string
    /** The channel the message was sent in. */
    channelId: string
    /** The guild the message was sent in (if applicable). */
    guildId?: string
    /** The message content. */
    content: string
    /** The author of the message. */
    author: {
      /** The user's unique snowflake ID. */
      id: string
      /** The user's username (not unique across Discord). */
      username: string
      /** The user's Discord-tag (discriminator), if any. */
      discriminator?: number
      /** Whether this user is a bot account. */
      bot: boolean
    }
    /** Member properties of the author (if sent in a guild). */
    member?: {
      /** The user this member represents. */
      user: {
        /** The user's unique snowflake ID. */
        id: string
        /** The user's username (not unique across Discord). */
        username: string
        /** The user's Discord-tag (discriminator), if any. */
        discriminator?: number
        /** Whether this user is a bot account. */
        bot: boolean
      }
      /** The member's guild-specific nickname. */
      nick?: string
      /** The member's guild-specific avatar hash. */
      avatar?: string
      /** Role IDs assigned to this member. */
      roles: string[]
      /** ISO8601 timestamp when the member joined the guild. */
      joinedAt?: string
      /** ISO8601 timestamp when the member started boosting the guild. */
      premiumSince?: string
      /** Whether the member is deafened in voice channels. */
      deaf: boolean
      /** Whether the member is muted in voice channels. */
      mute: boolean
      /** Guild member flags. */
      flags: number
      /** Whether the member has not yet passed the guild's membership screening. */
      pending: boolean
      /** Total permissions of the member in the channel (only in interactions). */
      permissions?: string
      /** ISO8601 timestamp when the member's timeout expires. */
      communicationDisabledUntil?: string
    }
  }
  /** The full new message after the update (if available). */
  new?: {
    /** The user's unique snowflake ID. */
    id: string
    /** The channel the message was sent in. */
    channelId: string
    /** The guild the message was sent in (if applicable). */
    guildId?: string
    /** The message content. */
    content: string
    /** The author of the message. */
    author: {
      /** The user's unique snowflake ID. */
      id: string
      /** The user's username (not unique across Discord). */
      username: string
      /** The user's Discord-tag (discriminator), if any. */
      discriminator?: number
      /** Whether this user is a bot account. */
      bot: boolean
    }
    /** Member properties of the author (if sent in a guild). */
    member?: {
      /** The user this member represents. */
      user: {
        /** The user's unique snowflake ID. */
        id: string
        /** The user's username (not unique across Discord). */
        username: string
        /** The user's Discord-tag (discriminator), if any. */
        discriminator?: number
        /** Whether this user is a bot account. */
        bot: boolean
      }
      /** The member's guild-specific nickname. */
      nick?: string
      /** The member's guild-specific avatar hash. */
      avatar?: string
      /** Role IDs assigned to this member. */
      roles: string[]
      /** ISO8601 timestamp when the member joined the guild. */
      joinedAt?: string
      /** ISO8601 timestamp when the member started boosting the guild. */
      premiumSince?: string
      /** Whether the member is deafened in voice channels. */
      deaf: boolean
      /** Whether the member is muted in voice channels. */
      mute: boolean
      /** Guild member flags. */
      flags: number
      /** Whether the member has not yet passed the guild's membership screening. */
      pending: boolean
      /** Total permissions of the member in the channel (only in interactions). */
      permissions?: string
      /** ISO8601 timestamp when the member's timeout expires. */
      communicationDisabledUntil?: string
    }
  }
}

/**
 * Payload for a message delete event.
 *
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#message-delete).
 */
export type EventMessageDelete = {
  /** The deleted message's ID. */
  id: string
  /** The channel the message was in. */
  channelId: string
  /** The guild the message was in (if applicable). */
  guildId?: string
}

/**
 * Payload for a bulk message delete event.
 *
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#message-delete-bulk).
 */
export type EventMessageDeleteBulk = {
  /** IDs of the deleted messages. */
  ids: string[]
  /** The channel the messages were in. */
  channelId: string
  /** The guild the messages were in (if applicable). */
  guildId?: string
}

/**
 * Payload for the ready event, fired when the bot connects to the gateway.
 *
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#ready).
 */
export type EventReady = {
  /** The bot user. */
  user: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  /** IDs of guilds the bot is a member of. */
  guildIds: string[]
}

/**
 * Payload for an application command interaction.
 *
 * [Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object).
 */
export type EventInteractionCreate = {
  /** The interaction's unique snowflake ID. */
  interactionId: string
  /** Token for responding to this interaction. */
  interactionToken: string
  /** The application's ID. */
  applicationId: string
  /** The guild the interaction was triggered in. */
  guildId?: string
  /** The channel the interaction was triggered in. */
  channelId?: string
  /** The user this member represents. */
  user: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  /** Member properties of the user (if triggered in a guild). */
  member?: {
    /** The user this member represents. */
    user: {
      /** The user's unique snowflake ID. */
      id: string
      /** The user's username (not unique across Discord). */
      username: string
      /** The user's Discord-tag (discriminator), if any. */
      discriminator?: number
      /** Whether this user is a bot account. */
      bot: boolean
    }
    /** The member's guild-specific nickname. */
    nick?: string
    /** The member's guild-specific avatar hash. */
    avatar?: string
    /** Role IDs assigned to this member. */
    roles: string[]
    /** ISO8601 timestamp when the member joined the guild. */
    joinedAt?: string
    /** ISO8601 timestamp when the member started boosting the guild. */
    premiumSince?: string
    /** Whether the member is deafened in voice channels. */
    deaf: boolean
    /** Whether the member is muted in voice channels. */
    mute: boolean
    /** Guild member flags. */
    flags: number
    /** Whether the member has not yet passed the guild's membership screening. */
    pending: boolean
    /** Total permissions of the member in the channel (only in interactions). */
    permissions?: string
    /** ISO8601 timestamp when the member's timeout expires. */
    communicationDisabledUntil?: string
  }
  /** Name of the invoked command. */
  commandName: string
  /** Raw interaction data payload. */
  data: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** The user's locale. */
  locale?: string
  /** The guild's preferred locale. */
  guildLocale?: string
}

/**
 * Payload for a message component interaction (buttons, select menus).
 *
 * [Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object).
 */
export type EventComponentInteraction = {
  /** The interaction's unique snowflake ID. */
  interactionId: string
  /** Token for responding to this interaction. */
  interactionToken: string
  /** The application's ID. */
  applicationId: string
  /** The guild the interaction was triggered in. */
  guildId?: string
  /** The channel the interaction was triggered in. */
  channelId?: string
  /** The user this member represents. */
  user: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  /** Member properties of the user (if triggered in a guild). */
  member?: {
    /** The user this member represents. */
    user: {
      /** The user's unique snowflake ID. */
      id: string
      /** The user's username (not unique across Discord). */
      username: string
      /** The user's Discord-tag (discriminator), if any. */
      discriminator?: number
      /** Whether this user is a bot account. */
      bot: boolean
    }
    /** The member's guild-specific nickname. */
    nick?: string
    /** The member's guild-specific avatar hash. */
    avatar?: string
    /** Role IDs assigned to this member. */
    roles: string[]
    /** ISO8601 timestamp when the member joined the guild. */
    joinedAt?: string
    /** ISO8601 timestamp when the member started boosting the guild. */
    premiumSince?: string
    /** Whether the member is deafened in voice channels. */
    deaf: boolean
    /** Whether the member is muted in voice channels. */
    mute: boolean
    /** Guild member flags. */
    flags: number
    /** Whether the member has not yet passed the guild's membership screening. */
    pending: boolean
    /** Total permissions of the member in the channel (only in interactions). */
    permissions?: string
    /** ISO8601 timestamp when the member's timeout expires. */
    communicationDisabledUntil?: string
  }
  /** Raw component interaction data payload. */
  data: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** The user's locale. */
  locale?: string
  /** The guild's preferred locale. */
  guildLocale?: string
  /** ID of the message the component is attached to. */
  messageId?: string
}

export type EventModalSubmit = {
  interactionId: string
  interactionToken: string
  applicationId: string
  guildId?: string
  channelId?: string
  /** The user this member represents. */
  user: {
    /** The user's unique snowflake ID. */
    id: string
    /** The user's username (not unique across Discord). */
    username: string
    /** The user's Discord-tag (discriminator), if any. */
    discriminator?: number
    /** Whether this user is a bot account. */
    bot: boolean
  }
  member?: {
    /** The user this member represents. */
    user: {
      /** The user's unique snowflake ID. */
      id: string
      /** The user's username (not unique across Discord). */
      username: string
      /** The user's Discord-tag (discriminator), if any. */
      discriminator?: number
      /** Whether this user is a bot account. */
      bot: boolean
    }
    /** The member's guild-specific nickname. */
    nick?: string
    /** The member's guild-specific avatar hash. */
    avatar?: string
    /** Role IDs assigned to this member. */
    roles: string[]
    /** ISO8601 timestamp when the member joined the guild. */
    joinedAt?: string
    /** ISO8601 timestamp when the member started boosting the guild. */
    premiumSince?: string
    /** Whether the member is deafened in voice channels. */
    deaf: boolean
    /** Whether the member is muted in voice channels. */
    mute: boolean
    /** Guild member flags. */
    flags: number
    /** Whether the member has not yet passed the guild's membership screening. */
    pending: boolean
    /** Total permissions of the member in the channel (only in interactions). */
    permissions?: string
    /** ISO8601 timestamp when the member's timeout expires. */
    communicationDisabledUntil?: string
  }
  data: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  locale?: string
  guildLocale?: string
  messageId?: string
}

export type EventReaction = {
  userId?: string
  channelId: string
  messageId: string
  guildId?: string
  emoji: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  burst: boolean
}

export type EventReactionRemoveAll = {
  messageId: string
  channelId: string
  guildId?: string
}

/** Metadata associated with a KV key. */
export type RawKvKeyMetadata = {
  /** Unix timestamp (seconds) when this key expires. */
  expiration?: bigint
  /** Arbitrary JSON metadata attached to the key. */
  metadata?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
}

/** Information about a single KV key. */
export type RawKvKeyInfo = {
  /** The key's name. */
  name: string
  /** Unix timestamp (seconds) when this key expires. */
  expiration?: bigint
  /** Arbitrary JSON metadata attached to the key. */
  metadata?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
}

/** Result of listing keys in a KV store. */
export type RawKvListKeysResult = {
  /** The keys returned by this list operation. */
  keys: {
    /** The key's name. */
    name: string
    /** Unix timestamp (seconds) when this key expires. */
    expiration?: bigint
    /** Arbitrary JSON metadata attached to the key. */
    metadata?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  }[]
  /** Whether all matching keys have been returned. */
  listComplete: boolean
  /** Cursor for fetching the next page of results. */
  cursor?: string
}

/** Options for setting a KV key. */
export type RawKvSetOptions = {
  /** Unix timestamp (seconds) when this key should expire. */
  expiration?: bigint
  /** Arbitrary JSON metadata to attach to the key. */
  metadata?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
}

/** Options for listing keys in a KV store. */
export type RawKvListKeysOptions = {
  /** Only return keys starting with this prefix. */
  prefix?: string
  /** Maximum number of keys to return. */
  limit?: bigint
  /** Cursor from a previous list operation for pagination. */
  cursor?: string
}

/** Attachment to include in a message (either URL or base64-encoded data). */
export type RawAttachment =
  | {
      /** The URL to fetch the attachment from. */
      url: {
        /** The URL to fetch the attachment from. */
        url: string
        /** Filename for the attachment. */
        filename?: string
        /** Alt text / description for the attachment. */
        description?: string
      }
    }
  | {
      base64: {
        /** Base64-encoded file data. */
        data: string
        /** Filename for the attachment. */
        filename: string
        /** Alt text / description for the attachment. */
        description?: string
      }
    }

/** Media (image/video) for an embed. */
export type RawEmbedMedia = {
  /** URL of the media. */
  url?: string
}

/** Footer for an embed. */
export type RawEmbedFooter = {
  /** Footer text. */
  text?: string
  /** URL of the footer icon. */
  iconUrl?: string
}

/** Author for an embed. */
export type RawEmbedAuthor = {
  /** Author name. */
  name?: string
  /** URL when clicking the author name. */
  url?: string
  /** URL of the author icon. */
  iconUrl?: string
}

/** A field in an embed. */
export type RawEmbedField = {
  /** Field name (title). */
  name: string
  /** Field value (content). */
  value: string
  /** Whether to display inline with other fields. */
  inline: boolean
}

/**
 * A rich embed for a message.
 *
 * [Discord docs](https://discord.com/developers/docs/resources/message#embed-object).
 */
export type RawEmbed = {
  /** Embed title. */
  title?: string
  /** Embed description. */
  description?: string
  /** URL when clicking the author name. */
  url?: string
  /** Color code (decimal integer). */
  color?: number
  /** ISO8601 timestamp for the embed. */
  timestamp?: string
  /** Footer information. */
  footer?: {
    /** Footer text. */
    text?: string
    /** URL of the author icon. */
    iconUrl?: string
  }
  /** Image to display. */
  image?: {
    /** URL when clicking the author name. */
    url?: string
  }
  /** Thumbnail to display. */
  thumbnail?: {
    /** URL when clicking the author name. */
    url?: string
  }
  /** Author information. */
  author?: {
    /** Field name (title). */
    name?: string
    /** URL when clicking the author name. */
    url?: string
    /** URL of the author icon. */
    iconUrl?: string
  }
  /** Fields to display. */
  fields?: {
    /** Field name (title). */
    name: string
    /** Field value (content). */
    value: string
    /** Whether to display inline with other fields. */
    inline: boolean
  }[]
}

/**
 * Configuration for which mentions are allowed.
 *
 * [Discord docs](https://discord.com/developers/docs/resources/message#allowed-mentions-object).
 */
export type RawAllowedMentions = {
  /** Types of mentions to parse ("everyone", "users", "roles"). */
  parse?: string[]
  /** Specific user IDs allowed to be mentioned. */
  users?: string[]
  /** Specific role IDs allowed to be mentioned. */
  roles?: string[]
  /** Whether to mention the user being replied to. */
  repliedUser?: boolean
}

/** Arguments for sending a message. */
export type RawSendMessage = {
  /** The channel to send the message to. */
  channelId: string
  /** Message content. */
  content?: string
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Alt text / description for the attachment. */
    description?: string
    /** The URL to fetch the attachment from. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** The URL to fetch the attachment from. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Attachments to include. */
  attachments?:
    | {
        /** The URL to fetch the attachment from. */
        url: {
          /** The URL to fetch the attachment from. */
          url: string
          /** Filename for the attachment. */
          filename?: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }
    | {
        base64: {
          /** Base64-encoded file data. */
          data: string
          /** Filename for the attachment. */
          filename: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }[]
  /** Message components. */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Whether the message should be text-to-speech. */
  tts?: boolean
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Message flags bitmask. */
  flags?: bigint
  /** Deprecated: use reply_to instead. */
  messageId?: string
  /** Message ID to reply to. */
  replyTo?: string
}

/** Message options without routing fields. */
export type SendMessageOptions = Omit<RawSendMessage, 'channelId'>

/** Arguments for editing a message. */
export type RawEditMessage = {
  /** The channel containing the message. */
  channelId: string
  /** The message to edit. */
  messageId: string
  /** New message content. */
  content?: string
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Embed description. */
    description?: string
    /** URL when clicking the author name. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** URL when clicking the author name. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** URL when clicking the author name. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** URL when clicking the author name. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Message components. */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Message flags bitmask. */
  flags?: bigint
}

/** Arguments for deleting a message. */
export type RawDeleteMessage = {
  /** The channel containing the message. */
  channelId: string
  /** The message to delete. */
  messageId: string
}

/** Arguments for bulk deleting messages. */
export type RawBulkDeleteMessages = {
  /** The channel containing the messages. */
  channelId: string
  /** IDs of messages to delete (2-100). */
  messageIds: string[]
}

/** Arguments for pinning or unpinning a message. */
export type RawPinMessage = {
  /** The channel containing the message. */
  channelId: string
  /** The message to pin/unpin. */
  messageId: string
}

/** Arguments for adding or removing a reaction. */
export type RawReaction = {
  /** The channel containing the message. */
  channelId: string
  /** The message to react to. */
  messageId: string
  /** The emoji to use (unicode or custom format). */
  emoji: string
  /** User ID to remove reaction from (for remove only). */
  userId?: string
}

/** Arguments for clearing reactions from a message. */
export type RawClearReactions = {
  /** The channel containing the message. */
  channelId: string
  /** The message to clear reactions from. */
  messageId: string
  /** Specific emoji to clear (if omitted, clears all reactions). */
  emoji?: string
}

/** Arguments for fetching a single message. */
export type RawFetchMessage = {
  /** The channel containing the message. */
  channelId: string
  /** The message to fetch. */
  messageId: string
}

/** Arguments for fetching multiple messages from a channel. */
export type RawFetchMessages = {
  /** The channel to fetch messages from. */
  channelId: string
  /** Maximum number of messages to return (1-100). */
  limit?: number
  /** Fetch messages before this message ID. */
  before?: string
  /** Fetch messages after this message ID. */
  after?: string
  /** Fetch messages around this message ID. */
  around?: string
}

/** Arguments for crossposting a message to followers. */
export type RawCrosspostMessage = {
  /** The announcement channel containing the message. */
  channelId: string
  /** The message to crosspost. */
  messageId: string
}

/** Arguments for sending an initial interaction response. */
export type RawInteractionResponse = {
  /** The interaction's snowflake ID. */
  interactionId: string
  /** Token for this interaction. */
  token: string
  /** Message content. */
  content?: string
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Alt text / description for the attachment. */
    description?: string
    /** The URL to fetch the attachment from. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** The URL to fetch the attachment from. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Attachments to include. */
  attachments?:
    | {
        /** The URL to fetch the attachment from. */
        url: {
          /** The URL to fetch the attachment from. */
          url: string
          /** Filename for the attachment. */
          filename?: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }
    | {
        base64: {
          /** Base64-encoded file data. */
          data: string
          /** Filename for the attachment. */
          filename: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }[]
  /** Message components (buttons, select menus). */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Whether the message should be text-to-speech. */
  tts?: boolean
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Whether the response should be ephemeral (only visible to invoker). */
  ephemeral?: boolean
  /** Message flags bitmask. */
  flags?: bigint
}

/** Arguments for bulk-upserting guild application commands. */
export type RawUpsertGuildCommands = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The commands to register. */
  commands: {
    /** The option name. */
    name: string
    /** The option description. */
    description?: string
    /** Nested options (for subcommands/subcommand groups). */
    options?: {
      /** The option name. */
      name: string
      /** The option description. */
      description: string
      /** The option type (string, integer, boolean, etc.). */
      kind?: string
      /** Whether this option is required. */
      required?: boolean
      /** Nested options (for subcommands/subcommand groups). */
      options?: RawSlashCommandOption[]
    }[]
  }[]
}

/** Definition of a slash command. */
export type RawSlashCommand = {
  /** The option name. */
  name: string
  /** The option description. */
  description?: string
  /** Nested options (for subcommands/subcommand groups). */
  options?: {
    /** The option name. */
    name: string
    /** The option description. */
    description: string
    /** The option type (string, integer, boolean, etc.). */
    kind?: string
    /** Whether this option is required. */
    required?: boolean
    /** Nested options (for subcommands/subcommand groups). */
    options?: RawSlashCommandOption[]
  }[]
}

/** Definition of a slash command option. */
export type RawSlashCommandOption = {
  /** The option name. */
  name: string
  /** The option description. */
  description: string
  /** The option type (string, integer, boolean, etc.). */
  kind?: string
  /** Whether this option is required. */
  required?: boolean
  /** Nested options (for subcommands/subcommand groups). */
  options?: RawSlashCommandOption[]
}

/** Arguments for deferring an interaction response. */
export type RawDeferInteractionResponse = {
  /** The interaction's snowflake ID. */
  interactionId: string
  /** Token for this interaction. */
  token: string
  /** Whether the deferred response should be ephemeral. */
  ephemeral?: boolean
}

/** Arguments for updating a component interaction's message. */
export type RawUpdateInteractionResponse = {
  /** The interaction's snowflake ID. */
  interactionId: string
  /** Token for this interaction. */
  token: string
  /** New message content. */
  content?: string
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Alt text / description for the attachment. */
    description?: string
    /** The URL to fetch the attachment from. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** The URL to fetch the attachment from. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Attachments to include. */
  attachments?:
    | {
        /** The URL to fetch the attachment from. */
        url: {
          /** The URL to fetch the attachment from. */
          url: string
          /** Filename for the attachment. */
          filename?: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }
    | {
        base64: {
          /** Base64-encoded file data. */
          data: string
          /** Filename for the attachment. */
          filename: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }[]
  /** Message components. */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Whether the message should be text-to-speech. */
  tts?: boolean
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Message flags bitmask. */
  flags?: bigint
}

/** Arguments for editing the original interaction response. */
export type RawEditInteractionResponse = {
  /** Token for this interaction. */
  token: string
  /** New message content. */
  content?: string
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Alt text / description for the attachment. */
    description?: string
    /** The URL to fetch the attachment from. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** The URL to fetch the attachment from. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Attachments to include. */
  attachments?:
    | {
        /** The URL to fetch the attachment from. */
        url: {
          /** The URL to fetch the attachment from. */
          url: string
          /** Filename for the attachment. */
          filename?: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }
    | {
        base64: {
          /** Base64-encoded file data. */
          data: string
          /** Filename for the attachment. */
          filename: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }[]
  /** Message components. */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Message flags bitmask. */
  flags?: bigint
}

/** Arguments for deleting the original interaction response. */
export type RawDeleteInteractionResponse = {
  /** Token for this interaction. */
  token: string
}

/** Arguments for creating or editing a followup message. */
export type RawFollowupMessage = {
  /** Token for this interaction. */
  token: string
  /** Message ID (required when editing a followup). */
  messageId?: string
  /** Message content. */
  content?: string
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Alt text / description for the attachment. */
    description?: string
    /** The URL to fetch the attachment from. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** The URL to fetch the attachment from. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Attachments to include. */
  attachments?:
    | {
        /** The URL to fetch the attachment from. */
        url: {
          /** The URL to fetch the attachment from. */
          url: string
          /** Filename for the attachment. */
          filename?: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }
    | {
        base64: {
          /** Base64-encoded file data. */
          data: string
          /** Filename for the attachment. */
          filename: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }[]
  /** Message components. */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Whether the message should be text-to-speech. */
  tts?: boolean
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Message flags bitmask. */
  flags?: bigint
}

export type RawDeleteFollowupMessage = {
  token: string
  messageId: string
}

/** Arguments for creating a guild application command. */
export type RawCreateGuildCommand = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The command to create. */
  command: {
    /** The option name. */
    name: string
    /** The option description. */
    description?: string
    /** Nested options (for subcommands/subcommand groups). */
    options?: {
      /** The option name. */
      name: string
      /** The option description. */
      description: string
      /** The option type (string, integer, boolean, etc.). */
      kind?: string
      /** Whether this option is required. */
      required?: boolean
      /** Nested options (for subcommands/subcommand groups). */
      options?: RawSlashCommandOption[]
    }[]
  }
}

/** Arguments for editing a guild application command. */
export type RawEditGuildCommand = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The command's snowflake ID. */
  commandId: string
  /** Updated command data. */
  command: {
    /** The option name. */
    name: string
    /** The option description. */
    description?: string
    /** Nested options (for subcommands/subcommand groups). */
    options?: {
      /** The option name. */
      name: string
      /** The option description. */
      description: string
      /** The option type (string, integer, boolean, etc.). */
      kind?: string
      /** Whether this option is required. */
      required?: boolean
      /** Nested options (for subcommands/subcommand groups). */
      options?: RawSlashCommandOption[]
    }[]
  }
}

/** Arguments for deleting a guild application command. */
export type RawDeleteGuildCommand = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The command's snowflake ID. */
  commandId: string
}

/** Arguments for fetching a guild application command. */
export type RawGetGuildCommand = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The command's snowflake ID. */
  commandId: string
}

/** Arguments for editing guild command permissions. */
export type RawCommandPermissions = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The command's snowflake ID. */
  commandId: string
  /** New permissions payload. */
  permissions: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
}

/** Arguments containing only a guild ID. */
export type RawGuildId = {
  /** The guild's snowflake ID. */
  guildId: string
}

/** Arguments for operations targeting a user in a guild. */
export type RawGuildUser = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The user's snowflake ID. */
  userId: string
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for banning a member from a guild. */
export type RawBanMember = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The user's snowflake ID. */
  userId: string
  /** Seconds of message history to delete (0-604800). */
  deleteMessageSeconds?: number
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for adding or removing a role from a member. */
export type RawMemberRole = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The user's snowflake ID. */
  userId: string
  /** The role's snowflake ID. */
  roleId: string
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for editing a guild member. */
export type RawEditMember = {
  /** The guild's snowflake ID. */
  guildId: string
  /** The user's snowflake ID. */
  userId: string
  /** JSON payload with fields to update. */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for editing the current member in a guild. */
export type RawEditCurrentMember = {
  /** The guild's snowflake ID. */
  guildId: string
  /** JSON payload with fields to update (nick, avatar, banner, bio). */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for creating a guild channel. */
export type RawCreateChannel = {
  /** The guild's snowflake ID. */
  guildId: string
  /** JSON payload with channel properties. */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for editing a channel. */
export type RawEditChannel = {
  /** The channel's snowflake ID. */
  channelId: string
  /** JSON payload with updated properties. */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for deleting a channel. */
export type RawDeleteChannel = {
  /** The channel's snowflake ID. */
  channelId: string
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for creating a thread. */
export type RawCreateThread = {
  /** The parent channel's snowflake ID. */
  channelId: string
  /** JSON payload with thread properties. */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for creating a thread from a message. */
export type RawCreateThreadFromMessage = {
  /** The parent channel's snowflake ID. */
  channelId: string
  /** The message to start the thread from. */
  messageId: string
  /** JSON payload with thread properties. */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments containing only a thread ID. */
export type RawThreadId = {
  /** The thread's snowflake ID. */
  threadId: string
}

/** Arguments for adding or removing a thread member. */
export type RawThreadMember = {
  /** The thread's snowflake ID. */
  threadId: string
  /** The user's snowflake ID. */
  userId: string
}

/** Arguments for executing a webhook. */
export type RawExecuteWebhook = {
  /** The webhook's snowflake ID. */
  webhookId: string
  /** The webhook token. */
  token: string
  /** Whether to wait for message creation and return it. */
  wait?: boolean
  /** Thread ID to send the message to (if in a forum/thread channel). */
  threadId?: string
  /** Whether to include components (requires specific permissions). */
  withComponents?: boolean
  /** Message content. */
  content?: string
  /** Override the webhook's default username. */
  username?: string
  /** Override the webhook's default avatar. */
  avatarUrl?: string
  /** Whether the message should be text-to-speech. */
  tts?: boolean
  /** Embeds to include. */
  embeds?: {
    /** Embed title. */
    title?: string
    /** Alt text / description for the attachment. */
    description?: string
    /** The URL to fetch the attachment from. */
    url?: string
    /** Color code (decimal integer). */
    color?: number
    /** ISO8601 timestamp for the embed. */
    timestamp?: string
    /** Footer information. */
    footer?: {
      /** Footer text. */
      text?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Image to display. */
    image?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Thumbnail to display. */
    thumbnail?: {
      /** The URL to fetch the attachment from. */
      url?: string
    }
    /** Author information. */
    author?: {
      /** Field name (title). */
      name?: string
      /** The URL to fetch the attachment from. */
      url?: string
      /** URL of the author icon. */
      iconUrl?: string
    }
    /** Fields to display. */
    fields?: {
      /** Field name (title). */
      name: string
      /** Field value (content). */
      value: string
      /** Whether to display inline with other fields. */
      inline: boolean
    }[]
  }[]
  /** Attachments to include. */
  attachments?:
    | {
        /** The URL to fetch the attachment from. */
        url: {
          /** The URL to fetch the attachment from. */
          url: string
          /** Filename for the attachment. */
          filename?: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }
    | {
        base64: {
          /** Base64-encoded file data. */
          data: string
          /** Filename for the attachment. */
          filename: string
          /** Alt text / description for the attachment. */
          description?: string
        }
      }[]
  /** Message components. */
  components?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null[]
  /** Allowed mentions configuration. */
  allowedMentions?: {
    /** Types of mentions to parse ("everyone", "users", "roles"). */
    parse?: string[]
    /** Specific user IDs allowed to be mentioned. */
    users?: string[]
    /** Specific role IDs allowed to be mentioned. */
    roles?: string[]
    /** Whether to mention the user being replied to. */
    repliedUser?: boolean
  }
  /** Message flags bitmask. */
  flags?: bigint
  /** Name for the created thread (forum channels). */
  threadName?: string
}

/** Arguments for editing a webhook. */
export type RawEditWebhook = {
  /** The webhook's snowflake ID. */
  webhookId: string
  /** The webhook token (if using tokenized endpoint). */
  token?: string
  /** JSON payload with updated properties. */
  payload: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null
  /** Audit log reason for this action. */
  reason?: string
}

/** Arguments for deleting a webhook. */
export type RawDeleteWebhook = {
  /** The webhook's snowflake ID. */
  webhookId: string
  /** The webhook token (if using tokenized endpoint). */
  token?: string
  /** Audit log reason for this action. */
  reason?: string
}

export type ButtonStyle = 1 | 2 | 3 | 4

export const ButtonStyle = {
  Primary: 1,
  Secondary: 2,
  Success: 3,
  Danger: 4
} as const

export type ComponentType =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 17
  | 18
  | 19

export const ComponentType = {
  ActionRow: 1,
  Button: 2,
  StringSelect: 3,
  InputText: 4,
  UserSelect: 5,
  RoleSelect: 6,
  MentionableSelect: 7,
  ChannelSelect: 8,
  Section: 9,
  TextDisplay: 10,
  Thumbnail: 11,
  MediaGallery: 12,
  File: 13,
  Separator: 14,
  Container: 17,
  Label: 18,
  FileUpload: 19
} as const

export type InputTextStyle = 1 | 2

export const InputTextStyle = {
  Short: 1,
  Paragraph: 2
} as const

export type MessageFlags = number

export const MessageFlags = {
  CROSSPOSTED: 1,
  IS_CROSSPOST: 2,
  SUPPRESS_EMBEDS: 4,
  SOURCE_MESSAGE_DELETED: 8,
  URGENT: 16,
  HAS_THREAD: 32,
  EPHEMERAL: 64,
  LOADING: 128,
  FAILED_TO_MENTION_SOME_ROLES_IN_THREAD: 256,
  SUPPRESS_NOTIFICATIONS: 4096,
  IS_VOICE_MESSAGE: 8192,
  IS_COMPONENTS_V2: 32768
} as const
