ignoreDepScripts: true
ignoreWorkspaceRootCheck: true
savePrefix: ''
shellEmulator: true

packages:
  - 'sdk'
  - 'examples/*'
  - 'apps/*'
  - 'packages/*'

catalog:
  '@typescript/native-preview': ^7.0.0-dev.20260105.1
  vitest: npm:@voidzero-dev/vite-plus-test@latest

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.11
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.11

onlyBuiltDependencies:
  - dprint
  - lefthook
