ignoreDepScripts: true
ignoreWorkspaceRootCheck: true
savePrefix: ''
shellEmulator: true

packages:
  - 'sdk'
  - 'examples/*'
  - 'apps/*'
  - 'packages/*'

catalog:
  vitest: npm:@voidzero-dev/vite-plus-test@latest

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-833c515fa25cef20905a7f9affb156dfa6f151ab
  vitest: npm:@voidzero-dev/vite-plus-test@0.0.0-833c515fa25cef20905a7f9affb156dfa6f151ab

onlyBuiltDependencies:
  - dprint
  - lefthook
