/**
 * Transform the rolldown-generated index.d.ts into a pure globals declaration file.
 *
 * This script:
 * 1. Reads sdk/dist/index.d.ts (generated by rolldown-plugin-dts)
 * 2. Removes the `export { ... }` line
 * 3. Adds global declarations for kv and EmbedBuilder (which can't be in index.ts due to conflicts)
 * 4. Outputs to sdk/dist/flora-globals.d.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const distDir = join(import.meta.dirname, "..", "dist");
const inputPath = join(distDir, "index.d.ts");
const outputPath = join(distDir, "flora-globals.d.ts");

let content = readFileSync(inputPath, "utf-8");

// Remove the export line at the end (matches: export { Type1, Type2, ... };)
content = content.replace(/^export\s*\{[^}]*\};\s*$/gm, "");

// Add the kv and EmbedBuilder globals that couldn't be in index.ts
// These need to be added inside the `declare global { ... }` block
const kvAndEmbedBuilderGlobals = `  // SDK objects (added by generate-globals.ts)
  const kv: {
    store(name: string): KvStore;
  };
  const EmbedBuilder: typeof EmbedBuilder;
`;

// Find the closing brace of `declare global {` and insert before it.
// The pattern is: we find `declare global {` and then match until the closing `}`
// We look for the last `}` that closes the declare global block (followed by optional whitespace
// and then //#endregion or end of section)
content = content.replace(
  /(declare global \{[\s\S]*?)(^\})/m,
  `$1${kvAndEmbedBuilderGlobals}$2`
);

const output = `// Flora SDK Global Type Definitions
// Auto-generated from sdk/dist/index.d.ts - do not edit manually
// Regenerate: cd sdk && bun run build

// This export makes this file a module, which is required for "declare global" to work
export {};

${content.trim()}
`;

writeFileSync(outputPath, output);
console.log(`Generated ${outputPath}`);
