use std::{fs, path::PathBuf};

use flora::{
    discord_handler::{
        EventComponentInteraction, EventInteractionCreate, EventMember, EventMessage,
        EventMessageDelete, EventMessageDeleteBulk, EventMessageUpdate, EventModalSubmit,
        EventReaction, EventReactionRemoveAll, EventReady, EventUser,
    },
    kv::{RawKvKeyInfo, RawKvKeyMetadata, RawKvListKeysResult},
    ops::{
        channels::{
            RawCreateChannel, RawCreateThread, RawCreateThreadFromMessage, RawDeleteChannel,
            RawEditChannel, RawThreadId, RawThreadMember,
        },
        commands::{
            RawCommandPermissions, RawCreateGuildCommand, RawDeleteGuildCommand,
            RawEditGuildCommand, RawGetGuildCommand, RawGuildId,
        },
        guilds::{RawBanMember, RawEditMember, RawGuildUser, RawMemberRole},
        interaction::{
            RawDeferInteractionResponse, RawDeleteFollowupMessage, RawDeleteInteractionResponse,
            RawEditInteractionResponse, RawFollowupMessage, RawInteractionResponse,
            RawSlashCommand, RawSlashCommandOption, RawUpdateInteractionResponse,
            RawUpsertGuildCommands,
        },
        kv::{RawKvListKeysOptions, RawKvSetOptions},
        message::{
            RawAllowedMentions, RawAttachment, RawBulkDeleteMessages, RawClearReactions,
            RawCrosspostMessage, RawDeleteMessage, RawEditMessage, RawEmbed, RawEmbedAuthor,
            RawEmbedField, RawEmbedFooter, RawEmbedMedia, RawFetchMessage, RawFetchMessages,
            RawPinMessage, RawReaction, RawSendMessage,
        },
        webhooks::{RawDeleteWebhook, RawEditWebhook, RawExecuteWebhook},
    },
};
use t0x::{export, serde_json::json_value_def};

fn main() {
    let output_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../sdk/src")
        .canonicalize()
        .expect("Failed to resolve output path")
        .join("generated.ts");

    let mut output =
        String::from("// This file is auto-generated by typegen. Do not edit manually.\n\n");

    // JsonValue type used by serde_json::Value fields
    output.push_str(&json_value_def());
    output.push('\n');

    output.push_str(&export!(
        // Event payloads
        EventUser,
        EventMember,
        EventMessage,
        EventMessageUpdate,
        EventMessageDelete,
        EventMessageDeleteBulk,
        EventReady,
        EventInteractionCreate,
        EventComponentInteraction,
        EventModalSubmit,
        EventReaction,
        EventReactionRemoveAll,
        // KV types
        RawKvKeyMetadata,
        RawKvKeyInfo,
        RawKvListKeysResult,
        RawKvSetOptions,
        RawKvListKeysOptions,
        // Message types
        RawAttachment,
        RawEmbedMedia,
        RawEmbedFooter,
        RawEmbedAuthor,
        RawEmbedField,
        RawEmbed,
        RawAllowedMentions,
        RawSendMessage,
        RawEditMessage,
        RawDeleteMessage,
        RawBulkDeleteMessages,
        RawPinMessage,
        RawReaction,
        RawClearReactions,
        RawFetchMessage,
        RawFetchMessages,
        RawCrosspostMessage,
        // Interaction types
        RawInteractionResponse,
        RawUpsertGuildCommands,
        RawSlashCommand,
        RawSlashCommandOption,
        RawDeferInteractionResponse,
        RawUpdateInteractionResponse,
        RawEditInteractionResponse,
        RawDeleteInteractionResponse,
        RawFollowupMessage,
        RawDeleteFollowupMessage,
        // Command types
        RawCreateGuildCommand,
        RawEditGuildCommand,
        RawDeleteGuildCommand,
        RawGetGuildCommand,
        RawCommandPermissions,
        RawGuildId,
        // Guild types
        RawGuildUser,
        RawBanMember,
        RawMemberRole,
        RawEditMember,
        // Channel types
        RawCreateChannel,
        RawEditChannel,
        RawDeleteChannel,
        RawCreateThread,
        RawCreateThreadFromMessage,
        RawThreadId,
        RawThreadMember,
        // Webhook types
        RawExecuteWebhook,
        RawEditWebhook,
        RawDeleteWebhook,
    ));

    fs::write(&output_path, output).expect("Failed to write generated types");
    println!("Generated types written to {}", output_path.display());
}
