// This file is auto-generated by typegen. Do not edit manually.

/**
 * A Discord user.
 * 
 * [Discord docs](https://discord.com/developers/docs/resources/user#user-object).
 */
type EventUser = {
	/** The user's unique snowflake ID. */
	id: string;
	/** The user's username (not unique across Discord). */
	username: string;
	/** The user's Discord-tag (discriminator), if any. */
	discriminator?: number;
	/** Whether this user is a bot account. */
	bot: boolean;
};

/**
 * A member of a guild.
 * 
 * [Discord docs](https://discord.com/developers/docs/resources/guild#guild-member-object).
 */
type EventMember = {
	/** The user this member represents. */
	user: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	/** The member's guild-specific nickname. */
	nick?: string;
	/** The member's guild-specific avatar hash. */
	avatar?: string;
	/** Role IDs assigned to this member. */
	roles: string[];
	/** ISO8601 timestamp when the member joined the guild. */
	joined_at?: string;
	/** ISO8601 timestamp when the member started boosting the guild. */
	premium_since?: string;
	/** Whether the member is deafened in voice channels. */
	deaf: boolean;
	/** Whether the member is muted in voice channels. */
	mute: boolean;
	/** Guild member flags. */
	flags: number;
	/** Whether the member has not yet passed the guild's membership screening. */
	pending: boolean;
	/** Total permissions of the member in the channel (only in interactions). */
	permissions?: string;
	/** ISO8601 timestamp when the member's timeout expires. */
	communication_disabled_until?: string;
};

/**
 * A message sent in a channel.
 * 
 * [Discord docs](https://discord.com/developers/docs/resources/message#message-object).
 */
type EventMessage = {
	/** The user's unique snowflake ID. */
	id: string;
	/** The channel the message was sent in. */
	channel_id: string;
	/** The guild the message was sent in (if applicable). */
	guild_id?: string;
	/** The message content. */
	content: string;
	/** The author of the message. */
	author: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	/** Member properties of the author (if sent in a guild). */
	member?: {
		/** The user this member represents. */
		user: {
			/** The user's unique snowflake ID. */
			id: string;
			/** The user's username (not unique across Discord). */
			username: string;
			/** The user's Discord-tag (discriminator), if any. */
			discriminator?: number;
			/** Whether this user is a bot account. */
			bot: boolean;
		};
		/** The member's guild-specific nickname. */
		nick?: string;
		/** The member's guild-specific avatar hash. */
		avatar?: string;
		/** Role IDs assigned to this member. */
		roles: string[];
		/** ISO8601 timestamp when the member joined the guild. */
		joined_at?: string;
		/** ISO8601 timestamp when the member started boosting the guild. */
		premium_since?: string;
		/** Whether the member is deafened in voice channels. */
		deaf: boolean;
		/** Whether the member is muted in voice channels. */
		mute: boolean;
		/** Guild member flags. */
		flags: number;
		/** Whether the member has not yet passed the guild's membership screening. */
		pending: boolean;
		/** Total permissions of the member in the channel (only in interactions). */
		permissions?: string;
		/** ISO8601 timestamp when the member's timeout expires. */
		communication_disabled_until?: string;
	};
};

/**
 * Payload for a message update event.
 * 
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#message-update).
 */
type EventMessageUpdate = {
	/** The user's unique snowflake ID. */
	id: string;
	/** The channel the message was sent in. */
	channel_id: string;
	/** The guild the message was sent in (if applicable). */
	guild_id?: string;
	/** The message content. */
	content?: string;
	/** The author of the message. */
	author?: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	/** ISO8601 timestamp when the message was edited. */
	edited_timestamp?: string;
	/** The cached old message before the update (if available). */
	old?: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The channel the message was sent in. */
		channel_id: string;
		/** The guild the message was sent in (if applicable). */
		guild_id?: string;
		/** The message content. */
		content: string;
		/** The author of the message. */
		author: {
			/** The user's unique snowflake ID. */
			id: string;
			/** The user's username (not unique across Discord). */
			username: string;
			/** The user's Discord-tag (discriminator), if any. */
			discriminator?: number;
			/** Whether this user is a bot account. */
			bot: boolean;
		};
		/** Member properties of the author (if sent in a guild). */
		member?: {
			/** The user this member represents. */
			user: {
				/** The user's unique snowflake ID. */
				id: string;
				/** The user's username (not unique across Discord). */
				username: string;
				/** The user's Discord-tag (discriminator), if any. */
				discriminator?: number;
				/** Whether this user is a bot account. */
				bot: boolean;
			};
			/** The member's guild-specific nickname. */
			nick?: string;
			/** The member's guild-specific avatar hash. */
			avatar?: string;
			/** Role IDs assigned to this member. */
			roles: string[];
			/** ISO8601 timestamp when the member joined the guild. */
			joined_at?: string;
			/** ISO8601 timestamp when the member started boosting the guild. */
			premium_since?: string;
			/** Whether the member is deafened in voice channels. */
			deaf: boolean;
			/** Whether the member is muted in voice channels. */
			mute: boolean;
			/** Guild member flags. */
			flags: number;
			/** Whether the member has not yet passed the guild's membership screening. */
			pending: boolean;
			/** Total permissions of the member in the channel (only in interactions). */
			permissions?: string;
			/** ISO8601 timestamp when the member's timeout expires. */
			communication_disabled_until?: string;
		};
	};
	/** The full new message after the update (if available). */
	new?: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The channel the message was sent in. */
		channel_id: string;
		/** The guild the message was sent in (if applicable). */
		guild_id?: string;
		/** The message content. */
		content: string;
		/** The author of the message. */
		author: {
			/** The user's unique snowflake ID. */
			id: string;
			/** The user's username (not unique across Discord). */
			username: string;
			/** The user's Discord-tag (discriminator), if any. */
			discriminator?: number;
			/** Whether this user is a bot account. */
			bot: boolean;
		};
		/** Member properties of the author (if sent in a guild). */
		member?: {
			/** The user this member represents. */
			user: {
				/** The user's unique snowflake ID. */
				id: string;
				/** The user's username (not unique across Discord). */
				username: string;
				/** The user's Discord-tag (discriminator), if any. */
				discriminator?: number;
				/** Whether this user is a bot account. */
				bot: boolean;
			};
			/** The member's guild-specific nickname. */
			nick?: string;
			/** The member's guild-specific avatar hash. */
			avatar?: string;
			/** Role IDs assigned to this member. */
			roles: string[];
			/** ISO8601 timestamp when the member joined the guild. */
			joined_at?: string;
			/** ISO8601 timestamp when the member started boosting the guild. */
			premium_since?: string;
			/** Whether the member is deafened in voice channels. */
			deaf: boolean;
			/** Whether the member is muted in voice channels. */
			mute: boolean;
			/** Guild member flags. */
			flags: number;
			/** Whether the member has not yet passed the guild's membership screening. */
			pending: boolean;
			/** Total permissions of the member in the channel (only in interactions). */
			permissions?: string;
			/** ISO8601 timestamp when the member's timeout expires. */
			communication_disabled_until?: string;
		};
	};
};

/**
 * Payload for a message delete event.
 * 
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#message-delete).
 */
type EventMessageDelete = {
	/** The deleted message's ID. */
	id: string;
	/** The channel the message was in. */
	channel_id: string;
	/** The guild the message was in (if applicable). */
	guild_id?: string;
};

/**
 * Payload for a bulk message delete event.
 * 
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#message-delete-bulk).
 */
type EventMessageDeleteBulk = {
	/** IDs of the deleted messages. */
	ids: string[];
	/** The channel the messages were in. */
	channel_id: string;
	/** The guild the messages were in (if applicable). */
	guild_id?: string;
};

/**
 * Payload for the ready event, fired when the bot connects to the gateway.
 * 
 * [Discord docs](https://discord.com/developers/docs/events/gateway-events#ready).
 */
type EventReady = {
	/** The bot user. */
	user: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	/** IDs of guilds the bot is a member of. */
	guild_ids: string[];
};

/**
 * Payload for an application command interaction.
 * 
 * [Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object).
 */
type EventInteractionCreate = {
	/** The interaction's unique snowflake ID. */
	interaction_id: string;
	/** Token for responding to this interaction. */
	interaction_token: string;
	/** The application's ID. */
	application_id: string;
	/** The guild the interaction was triggered in. */
	guild_id?: string;
	/** The channel the interaction was triggered in. */
	channel_id?: string;
	/** The user this member represents. */
	user: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	/** Member properties of the user (if triggered in a guild). */
	member?: {
		/** The user this member represents. */
		user: {
			/** The user's unique snowflake ID. */
			id: string;
			/** The user's username (not unique across Discord). */
			username: string;
			/** The user's Discord-tag (discriminator), if any. */
			discriminator?: number;
			/** Whether this user is a bot account. */
			bot: boolean;
		};
		/** The member's guild-specific nickname. */
		nick?: string;
		/** The member's guild-specific avatar hash. */
		avatar?: string;
		/** Role IDs assigned to this member. */
		roles: string[];
		/** ISO8601 timestamp when the member joined the guild. */
		joined_at?: string;
		/** ISO8601 timestamp when the member started boosting the guild. */
		premium_since?: string;
		/** Whether the member is deafened in voice channels. */
		deaf: boolean;
		/** Whether the member is muted in voice channels. */
		mute: boolean;
		/** Guild member flags. */
		flags: number;
		/** Whether the member has not yet passed the guild's membership screening. */
		pending: boolean;
		/** Total permissions of the member in the channel (only in interactions). */
		permissions?: string;
		/** ISO8601 timestamp when the member's timeout expires. */
		communication_disabled_until?: string;
	};
	/** Name of the invoked command. */
	command_name: string;
	/** Raw interaction data payload. */
	data: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** The user's locale. */
	locale?: string;
	/** The guild's preferred locale. */
	guild_locale?: string;
};

/**
 * Payload for a message component interaction (buttons, select menus).
 * 
 * [Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object).
 */
type EventComponentInteraction = {
	/** The interaction's unique snowflake ID. */
	interaction_id: string;
	/** Token for responding to this interaction. */
	interaction_token: string;
	/** The application's ID. */
	application_id: string;
	/** The guild the interaction was triggered in. */
	guild_id?: string;
	/** The channel the interaction was triggered in. */
	channel_id?: string;
	/** The user this member represents. */
	user: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	/** Member properties of the user (if triggered in a guild). */
	member?: {
		/** The user this member represents. */
		user: {
			/** The user's unique snowflake ID. */
			id: string;
			/** The user's username (not unique across Discord). */
			username: string;
			/** The user's Discord-tag (discriminator), if any. */
			discriminator?: number;
			/** Whether this user is a bot account. */
			bot: boolean;
		};
		/** The member's guild-specific nickname. */
		nick?: string;
		/** The member's guild-specific avatar hash. */
		avatar?: string;
		/** Role IDs assigned to this member. */
		roles: string[];
		/** ISO8601 timestamp when the member joined the guild. */
		joined_at?: string;
		/** ISO8601 timestamp when the member started boosting the guild. */
		premium_since?: string;
		/** Whether the member is deafened in voice channels. */
		deaf: boolean;
		/** Whether the member is muted in voice channels. */
		mute: boolean;
		/** Guild member flags. */
		flags: number;
		/** Whether the member has not yet passed the guild's membership screening. */
		pending: boolean;
		/** Total permissions of the member in the channel (only in interactions). */
		permissions?: string;
		/** ISO8601 timestamp when the member's timeout expires. */
		communication_disabled_until?: string;
	};
	/** Raw component interaction data payload. */
	data: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** The user's locale. */
	locale?: string;
	/** The guild's preferred locale. */
	guild_locale?: string;
	/** ID of the message the component is attached to. */
	message_id?: string;
};

type EventModalSubmit = {
	interaction_id: string;
	interaction_token: string;
	application_id: string;
	guild_id?: string;
	channel_id?: string;
	/** The user this member represents. */
	user: {
		/** The user's unique snowflake ID. */
		id: string;
		/** The user's username (not unique across Discord). */
		username: string;
		/** The user's Discord-tag (discriminator), if any. */
		discriminator?: number;
		/** Whether this user is a bot account. */
		bot: boolean;
	};
	member?: {
		/** The user this member represents. */
		user: {
			/** The user's unique snowflake ID. */
			id: string;
			/** The user's username (not unique across Discord). */
			username: string;
			/** The user's Discord-tag (discriminator), if any. */
			discriminator?: number;
			/** Whether this user is a bot account. */
			bot: boolean;
		};
		/** The member's guild-specific nickname. */
		nick?: string;
		/** The member's guild-specific avatar hash. */
		avatar?: string;
		/** Role IDs assigned to this member. */
		roles: string[];
		/** ISO8601 timestamp when the member joined the guild. */
		joined_at?: string;
		/** ISO8601 timestamp when the member started boosting the guild. */
		premium_since?: string;
		/** Whether the member is deafened in voice channels. */
		deaf: boolean;
		/** Whether the member is muted in voice channels. */
		mute: boolean;
		/** Guild member flags. */
		flags: number;
		/** Whether the member has not yet passed the guild's membership screening. */
		pending: boolean;
		/** Total permissions of the member in the channel (only in interactions). */
		permissions?: string;
		/** ISO8601 timestamp when the member's timeout expires. */
		communication_disabled_until?: string;
	};
	data: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	locale?: string;
	guild_locale?: string;
	message_id?: string;
};

type EventReaction = {
	user_id?: string;
	channel_id: string;
	message_id: string;
	guild_id?: string;
	emoji: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	burst: boolean;
};

type EventReactionRemoveAll = {
	message_id: string;
	channel_id: string;
	guild_id?: string;
};

/** Metadata associated with a KV key. */
type RawKvKeyMetadata = {
	/** Unix timestamp (seconds) when this key expires. */
	expiration?: bigint;
	/** Arbitrary JSON metadata attached to the key. */
	metadata?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
};

/** Information about a single KV key. */
type RawKvKeyInfo = {
	/** The key's name. */
	name: string;
	/** Unix timestamp (seconds) when this key expires. */
	expiration?: bigint;
	/** Arbitrary JSON metadata attached to the key. */
	metadata?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
};

/** Result of listing keys in a KV store. */
type RawKvListKeysResult = {
	/** The keys returned by this list operation. */
	keys: {
		/** The key's name. */
		name: string;
		/** Unix timestamp (seconds) when this key expires. */
		expiration?: bigint;
		/** Arbitrary JSON metadata attached to the key. */
		metadata?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	}[];
	/** Whether all matching keys have been returned. */
	list_complete: boolean;
	/** Cursor for fetching the next page of results. */
	cursor?: string;
};

/** Options for setting a KV key. */
type RawKvSetOptions = {
	/** Unix timestamp (seconds) when this key should expire. */
	expiration?: bigint;
	/** Arbitrary JSON metadata to attach to the key. */
	metadata?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
};

/** Options for listing keys in a KV store. */
type RawKvListKeysOptions = {
	/** Only return keys starting with this prefix. */
	prefix?: string;
	/** Maximum number of keys to return. */
	limit?: bigint;
	/** Cursor from a previous list operation for pagination. */
	cursor?: string;
};

/** Attachment to include in a message (either URL or base64-encoded data). */
type RawAttachment = {
	Url: {
		/** The URL to fetch the attachment from. */
		url: string;
		/** Filename for the attachment. */
		filename?: string;
		/** Alt text / description for the attachment. */
		description?: string;
	};
} | {
	Base64: {
		/** Base64-encoded file data. */
		data: string;
		/** Filename for the attachment. */
		filename: string;
		/** Alt text / description for the attachment. */
		description?: string;
	};
};

/** Media (image/video) for an embed. */
type RawEmbedMedia = {
	/** URL of the media. */
	url?: string;
};

/** Footer for an embed. */
type RawEmbedFooter = {
	/** Footer text. */
	text?: string;
	/** URL of the footer icon. */
	icon_url?: string;
};

/** Author for an embed. */
type RawEmbedAuthor = {
	/** Author name. */
	name?: string;
	/** URL when clicking the author name. */
	url?: string;
	/** URL of the author icon. */
	icon_url?: string;
};

/** A field in an embed. */
type RawEmbedField = {
	/** Field name (title). */
	name: string;
	/** Field value (content). */
	value: string;
	/** Whether to display inline with other fields. */
	inline: boolean;
};

/**
 * A rich embed for a message.
 * 
 * [Discord docs](https://discord.com/developers/docs/resources/message#embed-object).
 */
type RawEmbed = {
	/** Embed title. */
	title?: string;
	/** Embed description. */
	description?: string;
	/** URL when clicking the author name. */
	url?: string;
	/** Color code (decimal integer). */
	color?: number;
	/** ISO8601 timestamp for the embed. */
	timestamp?: string;
	/** Footer information. */
	footer?: {
		/** Footer text. */
		text?: string;
		/** URL of the author icon. */
		icon_url?: string;
	};
	/** Image to display. */
	image?: {
		/** URL when clicking the author name. */
		url?: string;
	};
	/** Thumbnail to display. */
	thumbnail?: {
		/** URL when clicking the author name. */
		url?: string;
	};
	/** Author information. */
	author?: {
		/** Field name (title). */
		name?: string;
		/** URL when clicking the author name. */
		url?: string;
		/** URL of the author icon. */
		icon_url?: string;
	};
	/** Fields to display. */
	fields?: {
		/** Field name (title). */
		name: string;
		/** Field value (content). */
		value: string;
		/** Whether to display inline with other fields. */
		inline: boolean;
	}[];
};

/**
 * Configuration for which mentions are allowed.
 * 
 * [Discord docs](https://discord.com/developers/docs/resources/message#allowed-mentions-object).
 */
type RawAllowedMentions = {
	/** Types of mentions to parse ("everyone", "users", "roles"). */
	parse?: string[];
	/** Specific user IDs allowed to be mentioned. */
	users?: string[];
	/** Specific role IDs allowed to be mentioned. */
	roles?: string[];
	/** Whether to mention the user being replied to. */
	replied_user?: boolean;
};

/** Arguments for sending a message. */
type RawSendMessage = {
	/** The channel to send the message to. */
	channel_id: string;
	/** Message content. */
	content?: string;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Alt text / description for the attachment. */
		description?: string;
		/** The URL to fetch the attachment from. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** The URL to fetch the attachment from. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Attachments to include. */
	attachments?: {
		Url: {
			/** The URL to fetch the attachment from. */
			url: string;
			/** Filename for the attachment. */
			filename?: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	} | {
		Base64: {
			/** Base64-encoded file data. */
			data: string;
			/** Filename for the attachment. */
			filename: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	}[];
	/** Message components. */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Whether the message should be text-to-speech. */
	tts?: boolean;
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Message flags bitmask. */
	flags?: bigint;
	/** Deprecated: use reply_to instead. */
	message_id?: string;
	/** Message ID to reply to. */
	reply_to?: string;
};

/** Arguments for editing a message. */
type RawEditMessage = {
	/** The channel containing the message. */
	channel_id: string;
	/** The message to edit. */
	message_id: string;
	/** New message content. */
	content?: string;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Embed description. */
		description?: string;
		/** URL when clicking the author name. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** URL when clicking the author name. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** URL when clicking the author name. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** URL when clicking the author name. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Message components. */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Message flags bitmask. */
	flags?: bigint;
};

/** Arguments for deleting a message. */
type RawDeleteMessage = {
	/** The channel containing the message. */
	channel_id: string;
	/** The message to delete. */
	message_id: string;
};

/** Arguments for bulk deleting messages. */
type RawBulkDeleteMessages = {
	/** The channel containing the messages. */
	channel_id: string;
	/** IDs of messages to delete (2-100). */
	message_ids: string[];
};

/** Arguments for pinning or unpinning a message. */
type RawPinMessage = {
	/** The channel containing the message. */
	channel_id: string;
	/** The message to pin/unpin. */
	message_id: string;
};

/** Arguments for sending an initial interaction response. */
type RawInteractionResponse = {
	/** The interaction's snowflake ID. */
	interaction_id: string;
	/** Token for this interaction. */
	token: string;
	/** Message content. */
	content?: string;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Alt text / description for the attachment. */
		description?: string;
		/** The URL to fetch the attachment from. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** The URL to fetch the attachment from. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Attachments to include. */
	attachments?: {
		Url: {
			/** The URL to fetch the attachment from. */
			url: string;
			/** Filename for the attachment. */
			filename?: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	} | {
		Base64: {
			/** Base64-encoded file data. */
			data: string;
			/** Filename for the attachment. */
			filename: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	}[];
	/** Message components (buttons, select menus). */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Whether the message should be text-to-speech. */
	tts?: boolean;
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Whether the response should be ephemeral (only visible to invoker). */
	ephemeral?: boolean;
	/** Message flags bitmask. */
	flags?: bigint;
};

/** Arguments for bulk-upserting guild application commands. */
type RawUpsertGuildCommands = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The commands to register. */
	commands: {
		/** The option name. */
		name: string;
		/** The option description. */
		description?: string;
		/** Nested options (for subcommands/subcommand groups). */
		options?: {
			/** The option name. */
			name: string;
			/** The option description. */
			description: string;
			/** The option type (string, integer, boolean, etc.). */
			kind?: string;
			/** Whether this option is required. */
			required?: boolean;
			/** Nested options (for subcommands/subcommand groups). */
			options?: RawSlashCommandOption[];
		}[];
	}[];
};

/** Definition of a slash command. */
type RawSlashCommand = {
	/** The option name. */
	name: string;
	/** The option description. */
	description?: string;
	/** Nested options (for subcommands/subcommand groups). */
	options?: {
		/** The option name. */
		name: string;
		/** The option description. */
		description: string;
		/** The option type (string, integer, boolean, etc.). */
		kind?: string;
		/** Whether this option is required. */
		required?: boolean;
		/** Nested options (for subcommands/subcommand groups). */
		options?: RawSlashCommandOption[];
	}[];
};

/** Definition of a slash command option. */
type RawSlashCommandOption = {
	/** The option name. */
	name: string;
	/** The option description. */
	description: string;
	/** The option type (string, integer, boolean, etc.). */
	kind?: string;
	/** Whether this option is required. */
	required?: boolean;
	/** Nested options (for subcommands/subcommand groups). */
	options?: RawSlashCommandOption[];
};

/** Arguments for deferring an interaction response. */
type RawDeferInteractionResponse = {
	/** The interaction's snowflake ID. */
	interaction_id: string;
	/** Token for this interaction. */
	token: string;
	/** Whether the deferred response should be ephemeral. */
	ephemeral?: boolean;
};

/** Arguments for updating a component interaction's message. */
type RawUpdateInteractionResponse = {
	/** The interaction's snowflake ID. */
	interaction_id: string;
	/** Token for this interaction. */
	token: string;
	/** New message content. */
	content?: string;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Alt text / description for the attachment. */
		description?: string;
		/** The URL to fetch the attachment from. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** The URL to fetch the attachment from. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Attachments to include. */
	attachments?: {
		Url: {
			/** The URL to fetch the attachment from. */
			url: string;
			/** Filename for the attachment. */
			filename?: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	} | {
		Base64: {
			/** Base64-encoded file data. */
			data: string;
			/** Filename for the attachment. */
			filename: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	}[];
	/** Message components. */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Whether the message should be text-to-speech. */
	tts?: boolean;
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Message flags bitmask. */
	flags?: bigint;
};

/** Arguments for editing the original interaction response. */
type RawEditInteractionResponse = {
	/** Token for this interaction. */
	token: string;
	/** New message content. */
	content?: string;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Alt text / description for the attachment. */
		description?: string;
		/** The URL to fetch the attachment from. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** The URL to fetch the attachment from. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Attachments to include. */
	attachments?: {
		Url: {
			/** The URL to fetch the attachment from. */
			url: string;
			/** Filename for the attachment. */
			filename?: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	} | {
		Base64: {
			/** Base64-encoded file data. */
			data: string;
			/** Filename for the attachment. */
			filename: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	}[];
	/** Message components. */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Message flags bitmask. */
	flags?: bigint;
};

/** Arguments for deleting the original interaction response. */
type RawDeleteInteractionResponse = {
	/** Token for this interaction. */
	token: string;
};

/** Arguments for creating or editing a followup message. */
type RawFollowupMessage = {
	/** Token for this interaction. */
	token: string;
	/** Message ID (required when editing a followup). */
	message_id?: string;
	/** Message content. */
	content?: string;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Alt text / description for the attachment. */
		description?: string;
		/** The URL to fetch the attachment from. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** The URL to fetch the attachment from. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Attachments to include. */
	attachments?: {
		Url: {
			/** The URL to fetch the attachment from. */
			url: string;
			/** Filename for the attachment. */
			filename?: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	} | {
		Base64: {
			/** Base64-encoded file data. */
			data: string;
			/** Filename for the attachment. */
			filename: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	}[];
	/** Message components. */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Whether the message should be text-to-speech. */
	tts?: boolean;
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Message flags bitmask. */
	flags?: bigint;
};

type RawDeleteFollowupMessage = {
	token: string;
	message_id: string;
};

/** Arguments for creating a guild application command. */
type RawCreateGuildCommand = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The command to create. */
	command: {
		/** The option name. */
		name: string;
		/** The option description. */
		description?: string;
		/** Nested options (for subcommands/subcommand groups). */
		options?: {
			/** The option name. */
			name: string;
			/** The option description. */
			description: string;
			/** The option type (string, integer, boolean, etc.). */
			kind?: string;
			/** Whether this option is required. */
			required?: boolean;
			/** Nested options (for subcommands/subcommand groups). */
			options?: RawSlashCommandOption[];
		}[];
	};
};

/** Arguments for editing a guild application command. */
type RawEditGuildCommand = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The command's snowflake ID. */
	command_id: string;
	/** Updated command data. */
	command: {
		/** The option name. */
		name: string;
		/** The option description. */
		description?: string;
		/** Nested options (for subcommands/subcommand groups). */
		options?: {
			/** The option name. */
			name: string;
			/** The option description. */
			description: string;
			/** The option type (string, integer, boolean, etc.). */
			kind?: string;
			/** Whether this option is required. */
			required?: boolean;
			/** Nested options (for subcommands/subcommand groups). */
			options?: RawSlashCommandOption[];
		}[];
	};
};

/** Arguments for deleting a guild application command. */
type RawDeleteGuildCommand = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The command's snowflake ID. */
	command_id: string;
};

/** Arguments for fetching a guild application command. */
type RawGetGuildCommand = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The command's snowflake ID. */
	command_id: string;
};

/** Arguments for editing guild command permissions. */
type RawCommandPermissions = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The command's snowflake ID. */
	command_id: string;
	/** New permissions payload. */
	permissions: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
};

/** Arguments containing only a guild ID. */
type RawGuildId = {
	/** The guild's snowflake ID. */
	guild_id: string;
};

/** Arguments for operations targeting a user in a guild. */
type RawGuildUser = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The user's snowflake ID. */
	user_id: string;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for banning a member from a guild. */
type RawBanMember = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The user's snowflake ID. */
	user_id: string;
	/** Seconds of message history to delete (0-604800). */
	delete_message_seconds?: number;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for adding or removing a role from a member. */
type RawMemberRole = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The user's snowflake ID. */
	user_id: string;
	/** The role's snowflake ID. */
	role_id: string;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for editing a guild member. */
type RawEditMember = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** The user's snowflake ID. */
	user_id: string;
	/** JSON payload with fields to update. */
	payload: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for creating a guild channel. */
type RawCreateChannel = {
	/** The guild's snowflake ID. */
	guild_id: string;
	/** JSON payload with channel properties. */
	payload: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for editing a channel. */
type RawEditChannel = {
	/** The channel's snowflake ID. */
	channel_id: string;
	/** JSON payload with updated properties. */
	payload: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for deleting a channel. */
type RawDeleteChannel = {
	/** The channel's snowflake ID. */
	channel_id: string;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for creating a thread. */
type RawCreateThread = {
	/** The parent channel's snowflake ID. */
	channel_id: string;
	/** JSON payload with thread properties. */
	payload: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for creating a thread from a message. */
type RawCreateThreadFromMessage = {
	/** The parent channel's snowflake ID. */
	channel_id: string;
	/** The message to start the thread from. */
	message_id: string;
	/** JSON payload with thread properties. */
	payload: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments containing only a thread ID. */
type RawThreadId = {
	/** The thread's snowflake ID. */
	thread_id: string;
};

/** Arguments for adding or removing a thread member. */
type RawThreadMember = {
	/** The thread's snowflake ID. */
	thread_id: string;
	/** The user's snowflake ID. */
	user_id: string;
};

/** Arguments for executing a webhook. */
type RawExecuteWebhook = {
	/** The webhook's snowflake ID. */
	webhook_id: string;
	/** The webhook token. */
	token: string;
	/** Whether to wait for message creation and return it. */
	wait?: boolean;
	/** Thread ID to send the message to (if in a forum/thread channel). */
	thread_id?: string;
	/** Whether to include components (requires specific permissions). */
	with_components?: boolean;
	/** Message content. */
	content?: string;
	/** Override the webhook's default username. */
	username?: string;
	/** Override the webhook's default avatar. */
	avatar_url?: string;
	/** Whether the message should be text-to-speech. */
	tts?: boolean;
	/** Embeds to include. */
	embeds?: {
		/** Embed title. */
		title?: string;
		/** Alt text / description for the attachment. */
		description?: string;
		/** The URL to fetch the attachment from. */
		url?: string;
		/** Color code (decimal integer). */
		color?: number;
		/** ISO8601 timestamp for the embed. */
		timestamp?: string;
		/** Footer information. */
		footer?: {
			/** Footer text. */
			text?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Image to display. */
		image?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Thumbnail to display. */
		thumbnail?: {
			/** The URL to fetch the attachment from. */
			url?: string;
		};
		/** Author information. */
		author?: {
			/** Field name (title). */
			name?: string;
			/** The URL to fetch the attachment from. */
			url?: string;
			/** URL of the author icon. */
			icon_url?: string;
		};
		/** Fields to display. */
		fields?: {
			/** Field name (title). */
			name: string;
			/** Field value (content). */
			value: string;
			/** Whether to display inline with other fields. */
			inline: boolean;
		}[];
	}[];
	/** Attachments to include. */
	attachments?: {
		Url: {
			/** The URL to fetch the attachment from. */
			url: string;
			/** Filename for the attachment. */
			filename?: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	} | {
		Base64: {
			/** Base64-encoded file data. */
			data: string;
			/** Filename for the attachment. */
			filename: string;
			/** Alt text / description for the attachment. */
			description?: string;
		};
	}[];
	/** Message components. */
	components?: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>[];
	/** Allowed mentions configuration. */
	allowed_mentions?: {
		/** Types of mentions to parse ("everyone", "users", "roles"). */
		parse?: string[];
		/** Specific user IDs allowed to be mentioned. */
		users?: string[];
		/** Specific role IDs allowed to be mentioned. */
		roles?: string[];
		/** Whether to mention the user being replied to. */
		replied_user?: boolean;
	};
	/** Message flags bitmask. */
	flags?: bigint;
	/** Name for the created thread (forum channels). */
	thread_name?: string;
};

/** Arguments for editing a webhook. */
type RawEditWebhook = {
	/** The webhook's snowflake ID. */
	webhook_id: string;
	/** The webhook token (if using tokenized endpoint). */
	token?: string;
	/** JSON payload with updated properties. */
	payload: number | string | boolean | null | JsonValue[] | Record<string, JsonValue>;
	/** Audit log reason for this action. */
	reason?: string;
};

/** Arguments for deleting a webhook. */
type RawDeleteWebhook = {
	/** The webhook's snowflake ID. */
	webhook_id: string;
	/** The webhook token (if using tokenized endpoint). */
	token?: string;
	/** Audit log reason for this action. */
	reason?: string;
};

