<script setup lang="ts">
import { Badge, Button, Input } from '@flora-internal/design-system'
import { ref } from 'vue'

const email = ref('tasky@uwu.network')
const dark = ref(false)
</script>

<template>
  <main :class="['min-h-dvh bg-background text-foreground', dark && 'dark']">
    <div class="mx-auto max-w-5xl px-6 py-12 lg:py-16">
      <header class="mb-10 flex flex-col gap-6 border-b border-border pb-8 md:flex-row md:items-end md:justify-between">
        <div class="space-y-3">
          <Badge>Flora UI</Badge>
          <div class="space-y-2">
            <h1 class="m-0 text-4xl font-750 tracking-tight md:text-5xl">
              Design-system showcase
            </h1>
            <p class="m-0 max-w-2xl text-muted-foreground">
              shadcn-vue components themed through the Flora UnoCSS Radix preset. Primary is Iris,
              neutral is Gray, and colors are exposed as Tailwind-compatible semantic tokens.
            </p>
          </div>
        </div>

        <Button variant="outline" @click="dark = !dark">
          {{ dark ? 'Use light mode' : 'Use dark mode' }}
        </Button>
      </header>

      <section class="grid gap-6 md:grid-cols-[1.15fr_0.85fr]">
        <div class="rounded-xl border border-border bg-card p-6 text-card-foreground shadow-sm">
          <div class="mb-6 flex items-center justify-between gap-4">
            <div>
              <h2 class="m-0 text-xl font-650">Buttons</h2>
              <p class="m-0 mt-1 text-sm text-muted-foreground">All variants generated by shadcn-vue.</p>
            </div>
            <Badge variant="secondary">primary: iris</Badge>
          </div>

          <div class="flex flex-wrap gap-3">
            <Button>Default</Button>
            <Button variant="secondary">Secondary</Button>
            <Button variant="outline">Outline</Button>
            <Button variant="ghost">Ghost</Button>
            <Button variant="link">Link</Button>
            <Button variant="destructive">Destructive</Button>
          </div>

          <div class="mt-6 flex flex-wrap items-center gap-3">
            <Button size="xs">Extra small</Button>
            <Button size="sm">Small</Button>
            <Button size="default">Default</Button>
            <Button size="lg">Large</Button>
            <Button size="icon" aria-label="Add item">+</Button>
          </div>
        </div>

        <div class="rounded-xl border border-border bg-card p-6 text-card-foreground shadow-sm">
          <h2 class="m-0 text-xl font-650">Form control</h2>
          <p class="m-0 mt-1 text-sm text-muted-foreground">Input inherits shadcn semantic colors.</p>

          <label class="mt-6 block space-y-2">
            <span class="text-sm font-500">Email</span>
            <Input v-model="email" placeholder="you@example.com" />
          </label>

          <div class="mt-4 rounded-lg border border-border bg-muted p-4 text-sm text-muted-foreground">
            Current value:
            <code class="text-foreground">{{ email || 'empty' }}</code>
          </div>
        </div>

        <div class="rounded-xl border border-border bg-card p-6 text-card-foreground shadow-sm md:col-span-2">
          <h2 class="m-0 text-xl font-650">Badges and Radix scale aliases</h2>
          <p class="m-0 mt-1 text-sm text-muted-foreground">
            Semantic tokens coexist with direct Radix scale utilities from the preset.
          </p>

          <div class="mt-6 flex flex-wrap gap-3">
            <Badge>Default</Badge>
            <Badge variant="secondary">Secondary</Badge>
            <Badge variant="outline">Outline</Badge>
            <Badge variant="destructive">Destructive</Badge>
          </div>

          <div class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div class="rounded-lg border border-iris-6 bg-iris-3 p-4 text-iris-12">
              <div class="font-650">Iris</div>
              <div class="text-sm text-iris-11">Primary accent scale</div>
            </div>
            <div class="rounded-lg border border-blue-6 bg-blue-3 p-4 text-blue-12">
              <div class="font-650">Blue</div>
              <div class="text-sm text-blue-11">Info scale</div>
            </div>
            <div class="rounded-lg border border-green-6 bg-green-3 p-4 text-green-12">
              <div class="font-650">Green</div>
              <div class="text-sm text-green-11">Success scale</div>
            </div>
            <div class="rounded-lg border border-red-6 bg-red-3 p-4 text-red-12">
              <div class="font-650">Red</div>
              <div class="text-sm text-red-11">Destructive scale</div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </main>
</template>
